export const mockPlayers = {
  count: 87,
  next: "https://swapi.co/api/people/?page=2",
  previous: null,
  results: [
    {
      name: "Luke Skywalker",
      height: "172",
      mass: "77",
      hair_color: "blond",
      skin_color: "fair",
      eye_color: "blue",
      birth_year: "19BBY",
      gender: "male",
      homeworld: {
        name: "Tatooine",
        rotation_period: "23",
        orbital_period: "304",
        diameter: "10465",
        climate: "arid",
        gravity: "1 standard",
        terrain: "desert",
        surface_water: "1",
        population: "200000",
        residents: [
          "https://swapi.co/api/people/1/",
          "https://swapi.co/api/people/2/",
          "https://swapi.co/api/people/4/",
          "https://swapi.co/api/people/6/",
          "https://swapi.co/api/people/7/",
          "https://swapi.co/api/people/8/",
          "https://swapi.co/api/people/9/",
          "https://swapi.co/api/people/11/",
          "https://swapi.co/api/people/43/",
          "https://swapi.co/api/people/62/"
        ],
        films: [
          "https://swapi.co/api/films/5/",
          "https://swapi.co/api/films/4/",
          "https://swapi.co/api/films/6/",
          "https://swapi.co/api/films/3/",
          "https://swapi.co/api/films/1/"
        ],
        created: "2014-12-09T13:50:49.641000Z",
        edited: "2014-12-21T20:48:04.175778Z",
        url: "https://swapi.co/api/planets/1/"
      },
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/",
        "https://swapi.co/api/films/7/"
      ],
      species: [
        {
          name: "Human",
          classification: "mammal",
          designation: "sentient",
          average_height: "180",
          skin_colors: "caucasian, black, asian, hispanic",
          hair_colors: "blonde, brown, black, red",
          eye_colors: "brown, blue, green, hazel, grey, amber",
          average_lifespan: "120",
          homeworld: {
            name: "Coruscant",
            rotation_period: "24",
            orbital_period: "368",
            diameter: "12240",
            climate: "temperate",
            gravity: "1 standard",
            terrain: "cityscape, mountains",
            surface_water: "unknown",
            population: "1000000000000",
            residents: [
              "https://swapi.co/api/people/34/",
              "https://swapi.co/api/people/55/",
              "https://swapi.co/api/people/74/"
            ],
            films: [
              "https://swapi.co/api/films/5/",
              "https://swapi.co/api/films/4/",
              "https://swapi.co/api/films/6/",
              "https://swapi.co/api/films/3/"
            ],
            created: "2014-12-10T11:54:13.921000Z",
            edited: "2014-12-20T20:58:18.432000Z",
            url: "https://swapi.co/api/planets/9/"
          },
          language: "Galactic Basic",
          people: [
            "https://swapi.co/api/people/1/",
            "https://swapi.co/api/people/4/",
            "https://swapi.co/api/people/5/",
            "https://swapi.co/api/people/6/",
            "https://swapi.co/api/people/7/",
            "https://swapi.co/api/people/9/",
            "https://swapi.co/api/people/10/",
            "https://swapi.co/api/people/11/",
            "https://swapi.co/api/people/12/",
            "https://swapi.co/api/people/14/",
            "https://swapi.co/api/people/18/",
            "https://swapi.co/api/people/19/",
            "https://swapi.co/api/people/21/",
            "https://swapi.co/api/people/22/",
            "https://swapi.co/api/people/25/",
            "https://swapi.co/api/people/26/",
            "https://swapi.co/api/people/28/",
            "https://swapi.co/api/people/29/",
            "https://swapi.co/api/people/32/",
            "https://swapi.co/api/people/34/",
            "https://swapi.co/api/people/43/",
            "https://swapi.co/api/people/51/",
            "https://swapi.co/api/people/60/",
            "https://swapi.co/api/people/61/",
            "https://swapi.co/api/people/62/",
            "https://swapi.co/api/people/66/",
            "https://swapi.co/api/people/67/",
            "https://swapi.co/api/people/68/",
            "https://swapi.co/api/people/69/",
            "https://swapi.co/api/people/74/",
            "https://swapi.co/api/people/81/",
            "https://swapi.co/api/people/84/",
            "https://swapi.co/api/people/85/",
            "https://swapi.co/api/people/86/",
            "https://swapi.co/api/people/35/"
          ],
          films: [
            "https://swapi.co/api/films/2/",
            "https://swapi.co/api/films/7/",
            "https://swapi.co/api/films/5/",
            "https://swapi.co/api/films/4/",
            "https://swapi.co/api/films/6/",
            "https://swapi.co/api/films/3/",
            "https://swapi.co/api/films/1/"
          ],
          created: "2014-12-10T13:52:11.567000Z",
          edited: "2015-04-17T06:59:55.850671Z",
          url: "https://swapi.co/api/species/1/"
        }
      ],
      vehicles: [
        "https://swapi.co/api/vehicles/14/",
        "https://swapi.co/api/vehicles/30/"
      ],
      starships: [
        "https://swapi.co/api/starships/12/",
        "https://swapi.co/api/starships/22/"
      ],
      created: "2014-12-09T13:50:51.644000Z",
      edited: "2014-12-20T21:17:56.891000Z",
      url: "https://swapi.co/api/people/1/"
    },
    {
      name: "C-3PO",
      height: "167",
      mass: "75",
      hair_color: "n/a",
      skin_color: "gold",
      eye_color: "yellow",
      birth_year: "112BBY",
      gender: "n/a",
      homeworld: "https://swapi.co/api/planets/1/",
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/5/",
        "https://swapi.co/api/films/4/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/"
      ],
      species: ["https://swapi.co/api/species/2/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:10:51.357000Z",
      edited: "2014-12-20T21:17:50.309000Z",
      url: "https://swapi.co/api/people/2/"
    },
    {
      name: "R2-D2",
      height: "96",
      mass: "32",
      hair_color: "n/a",
      skin_color: "white, blue",
      eye_color: "red",
      birth_year: "33BBY",
      gender: "n/a",
      homeworld: "https://swapi.co/api/planets/8/",
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/5/",
        "https://swapi.co/api/films/4/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/",
        "https://swapi.co/api/films/7/"
      ],
      species: ["https://swapi.co/api/species/2/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:11:50.376000Z",
      edited: "2014-12-20T21:17:50.311000Z",
      url: "https://swapi.co/api/people/3/"
    },
    {
      name: "Darth Vader",
      height: "202",
      mass: "136",
      hair_color: "none",
      skin_color: "white",
      eye_color: "yellow",
      birth_year: "41.9BBY",
      gender: "male",
      homeworld: "https://swapi.co/api/planets/1/",
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/"
      ],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: [],
      starships: ["https://swapi.co/api/starships/13/"],
      created: "2014-12-10T15:18:20.704000Z",
      edited: "2014-12-20T21:17:50.313000Z",
      url: "https://swapi.co/api/people/4/"
    },
    {
      name: "Leia Organa",
      height: "150",
      mass: "49",
      hair_color: "brown",
      skin_color: "light",
      eye_color: "brown",
      birth_year: "19BBY",
      gender: "female",
      homeworld: "https://swapi.co/api/planets/2/",
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/",
        "https://swapi.co/api/films/7/"
      ],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: ["https://swapi.co/api/vehicles/30/"],
      starships: [],
      created: "2014-12-10T15:20:09.791000Z",
      edited: "2014-12-20T21:17:50.315000Z",
      url: "https://swapi.co/api/people/5/"
    },
    {
      name: "Owen Lars",
      height: "178",
      mass: "120",
      hair_color: "brown, grey",
      skin_color: "light",
      eye_color: "blue",
      birth_year: "52BBY",
      gender: "male",
      homeworld: "https://swapi.co/api/planets/1/",
      films: [
        "https://swapi.co/api/films/5/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/1/"
      ],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:52:14.024000Z",
      edited: "2014-12-20T21:17:50.317000Z",
      url: "https://swapi.co/api/people/6/"
    },
    {
      name: "Beru Whitesun lars",
      height: "165",
      mass: "75",
      hair_color: "brown",
      skin_color: "light",
      eye_color: "blue",
      birth_year: "47BBY",
      gender: "female",
      homeworld: "https://swapi.co/api/planets/1/",
      films: [
        "https://swapi.co/api/films/5/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/1/"
      ],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:53:41.121000Z",
      edited: "2014-12-20T21:17:50.319000Z",
      url: "https://swapi.co/api/people/7/"
    },
    {
      name: "R5-D4",
      height: "97",
      mass: "32",
      hair_color: "n/a",
      skin_color: "white, red",
      eye_color: "red",
      birth_year: "unknown",
      gender: "n/a",
      homeworld: "https://swapi.co/api/planets/1/",
      films: ["https://swapi.co/api/films/1/"],
      species: ["https://swapi.co/api/species/2/"],
      vehicles: [],
      starships: [],
      created: "2014-12-10T15:57:50.959000Z",
      edited: "2014-12-20T21:17:50.321000Z",
      url: "https://swapi.co/api/people/8/"
    },
    {
      name: "Biggs Darklighter",
      height: "183",
      mass: "84",
      hair_color: "black",
      skin_color: "light",
      eye_color: "brown",
      birth_year: "24BBY",
      gender: "male",
      homeworld: "https://swapi.co/api/planets/1/",
      films: ["https://swapi.co/api/films/1/"],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: [],
      starships: ["https://swapi.co/api/starships/12/"],
      created: "2014-12-10T15:59:50.509000Z",
      edited: "2014-12-20T21:17:50.323000Z",
      url: "https://swapi.co/api/people/9/"
    },
    {
      name: "Obi-Wan Kenobi",
      height: "182",
      mass: "77",
      hair_color: "auburn, white",
      skin_color: "fair",
      eye_color: "blue-gray",
      birth_year: "57BBY",
      gender: "male",
      homeworld: "https://swapi.co/api/planets/20/",
      films: [
        "https://swapi.co/api/films/2/",
        "https://swapi.co/api/films/5/",
        "https://swapi.co/api/films/4/",
        "https://swapi.co/api/films/6/",
        "https://swapi.co/api/films/3/",
        "https://swapi.co/api/films/1/"
      ],
      species: ["https://swapi.co/api/species/1/"],
      vehicles: ["https://swapi.co/api/vehicles/38/"],
      starships: [
        "https://swapi.co/api/starships/48/",
        "https://swapi.co/api/starships/59/",
        "https://swapi.co/api/starships/64/",
        "https://swapi.co/api/starships/65/",
        "https://swapi.co/api/starships/74/"
      ],
      created: "2014-12-10T16:16:29.192000Z",
      edited: "2014-12-20T21:17:50.325000Z",
      url: "https://swapi.co/api/people/10/"
    }
  ]
};
